const sentences = [
  // Everyday conversation
  "Could you please give me a moment to think about that?",
  "I understand what you mean, but I see it a little differently.",
  "Would you mind explaining that one more time?",
  "I appreciate your help with this.",
  "I'm sorry, but I didn't quite catch what you said.",
  "That sounds like a good idea to me.",
  "Let me think about it, and I'll get back to you.",
  "I haven't made a final decision yet.",
  "It depends on what happens later today.",
  "I'm glad we had a chance to talk about this.",

  // Polite requests
  "Could you please speak a little more slowly?",
  "Would you mind giving me a hand with this?",
  "Could I borrow your phone for a moment?",
  "Please let me know when you are ready.",
  "Would it be possible to change the time?",
  "Could you show me how this works?",
  "Please feel free to ask if you have any questions.",
  "Would you please write that down for me?",
  "Could we discuss this in a little more detail?",
  "I'd appreciate it if you could send me a copy.",

  // Shopping and services
  "I'm looking for something practical and reasonably priced.",
  "Do you have this in a different size?",
  "Could you tell me how much this costs?",
  "I'd like to compare a few options before deciding.",
  "Is there a discount if I purchase more than one?",
  "Could I have a receipt, please?",
  "I'm afraid this isn't quite what I was looking for.",
  "What is your return policy?",
  "Could you recommend something similar?",
  "I'll take this one, please.",

  // Appointments and healthcare
  "Could we arrange an appointment for next week?",
  "I'd like to confirm my appointment for tomorrow.",
  "Is there anything available earlier in the day?",
  "I'm calling to reschedule my appointment.",
  "How long should I expect the appointment to take?",
  "I've been feeling unwell for the past few days.",
  "Could you explain the instructions more clearly?",
  "Should I take this medication with food?",
  "Please let me know if the symptoms get worse.",
  "I'd like to speak with the doctor in private.",

  // Telephone conversations
  "Hello, may I speak with Mr. Johnson, please?",
  "I'm calling regarding the message you left yesterday.",
  "Could you please hold for a moment?",
  "I'm afraid she's unavailable right now.",
  "Would you like to leave a message?",
  "Could you ask him to call me back?",
  "The connection isn't very clear.",
  "I'm sorry, I think we were disconnected.",
  "Could you repeat the last part of your message?",
  "Thank you for returning my call.",

  // Work and professional English
  "Let me check my schedule and get back to you.",
  "Please let me know if you need any additional information.",
  "I'd like to clarify one point before we continue.",
  "We should consider all the available options.",
  "I'll send you the updated document this afternoon.",
  "Could we move this discussion to tomorrow?",
  "I believe we've covered the most important issues.",
  "There may be a more efficient way to handle this.",
  "I'll make sure the work is completed on time.",
  "Thank you for bringing this to my attention.",

  // School and family
  "How did everything go at school today?",
  "Please remember to bring your homework with you.",
  "We need to leave the house by eight o'clock.",
  "Could you help me prepare dinner this evening?",
  "Let's talk about it when everyone gets home.",
  "I'll pick the children up after school.",
  "We haven't decided what to do this weekend.",
  "Please call me if your plans change.",
  "Everyone is looking forward to seeing you.",
  "We should spend more time together as a family.",

  // Travel and directions
  "Could you tell me how to get to the airport?",
  "How long does the journey usually take?",
  "I'd like to book a room for three nights.",
  "Does this bus go to the city centre?",
  "Could you let me know when we reach my stop?",
  "I'm afraid I may have taken the wrong road.",
  "Is breakfast included with the room?",
  "Where can I collect my luggage?",
  "Our flight has been delayed due to the weather.",
  "Could you recommend a good place to eat nearby?",

  // Social conversation
  "It was lovely speaking with you today.",
  "How have you been since we last met?",
  "Thank you very much for inviting me.",
  "I'm sorry I wasn't able to come yesterday.",
  "What have you been doing lately?",
  "I'd love to hear more about your trip.",
  "That reminds me of something that happened last week.",
  "We should get together again sometime soon.",
  "Please give my regards to your family.",
  "I hope you have a safe journey home.",

  // Confident natural English
  "As far as I know, everything is going according to plan.",
  "To be honest, I hadn't considered that possibility.",
  "That's a fair point, and I understand your concern.",
  "I may be mistaken, but I believe the meeting starts at ten.",
  "From my perspective, this is the best available option.",
  "I completely agree with what you just said.",
  "I'm not entirely convinced that will solve the problem.",
  "There seems to have been a misunderstanding.",
  "Let me make sure I understand you correctly.",
  "I'll do my best to have everything ready by tomorrow."
];

sentences.push(
  "The kettle is boiling.",
  "I woke up before the alarm this morning.",
  "My keys were underneath the newspaper.",
  "There is still some bread in the cupboard.",
  "The kitchen window faces the garden.",
  "I usually make my bed after breakfast.",
  "We ran out of soap yesterday.",
  "That towel is still damp.",
  "The front door needs a new handle.",
  "I left my glasses beside the sink.",
  "Our neighbour brought the parcel inside.",
  "The washing machine has finished its cycle.",
  "Put the clean plates on the top shelf.",
  "I opened the curtains to let some light in.",
  "This chair is more comfortable than it looks.",
  "Someone has moved the wastebasket.",
  "The floor is slippery near the doorway.",
  "We keep spare batteries in that drawer.",
  "By the time I got downstairs, breakfast was ready.",
  "It feels good to come home to a tidy room.",
  "What would you like for lunch?",
  "This soup smells wonderful.",
  "I prefer my tea without sugar.",
  "The rice needs a few more minutes.",
  "We bought fresh tomatoes at the market.",
  "There is enough food for everyone.",
  "I forgot to put the milk in the fridge.",
  "Slice the onions as thinly as you can.",
  "That sauce is a little too spicy for me.",
  "Have you tried the roasted vegetables?",
  "I packed a sandwich for the journey.",
  "The bread is soft in the middle and crisp outside.",
  "We can use the leftovers tomorrow.",
  "My sister taught me how to make this stew.",
  "I am hungry, but I cannot manage a large meal.",
  "The recipe calls for a teaspoon of salt.",
  "Let the cake cool before cutting it.",
  "Which fruit is in season at the moment?",
  "I spilled some flour on the counter.",
  "Cooking together makes the evening more enjoyable.",
  "Is this seat taken?",
  "We are ready to order.",
  "I ordered the grilled fish, not the chicken.",
  "May we have some drinking water for the table?",
  "The menu is written on the board.",
  "I would like the dressing on the side.",
  "Does this dish contain peanuts?",
  "My friend is allergic to shellfish.",
  "We have been waiting for our main course.",
  "That was delicious, especially the sauce.",
  "Can we pay separately?",
  "I think there is an extra item on the bill.",
  "The restaurant closes earlier on Sundays.",
  "We found a quiet table near the window.",
  "I am saving room for dessert.",
  "The portion was larger than I expected.",
  "Our food arrived while you were outside.",
  "Do you serve breakfast all day?",
  "We can share a plate if you are not very hungry.",
  "Please pack the rest for me to take home.",
  "These shoes pinch my toes.",
  "The blue shirt fits better than the green one.",
  "I only came in for a loaf of bread.",
  "Where do you keep the washing powder?",
  "This packet has already been opened.",
  "The price on the shelf is different.",
  "I brought my own shopping bag.",
  "Do these batteries come with the torch?",
  "I need a smaller bag of rice.",
  "The queue is moving quite quickly.",
  "We can check another shop across the road.",
  "These oranges are sold by weight.",
  "I am just browsing, thank you.",
  "The zip on this jacket is broken.",
  "Have you got any plain notebooks?",
  "This fabric feels soft against my skin.",
  "I bought the wrong type of charger.",
  "The shopkeeper put the fragile items in a separate box.",
  "I would rather buy something that lasts.",
  "We stayed within our budget this week.",
  "The bus is nearly full.",
  "I missed my stop because I was distracted.",
  "We should cross at the traffic lights.",
  "The driver took a different route today.",
  "How much is a ticket to the next town?",
  "I have the exact fare.",
  "The train leaves from the opposite platform.",
  "There is a long queue at the taxi stand.",
  "My bicycle has a flat tyre.",
  "The road is closed for repairs.",
  "We were stuck in traffic for almost an hour.",
  "I prefer to walk when the weather is pleasant.",
  "Watch out for the motorcycle behind you.",
  "The bus shelter kept us dry.",
  "I will meet you outside the station entrance.",
  "This is the last bus of the evening.",
  "The journey was smoother than I expected.",
  "We need to change trains at the next station.",
  "I left home early so I would not have to rush.",
  "The driver waited until everyone was seated."
);